<a href="https://colab.research.google.com/github/gracekazungu/Ada-Lab-Web/blob/main/Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd#import pandas
df = pd.read_csv("survey_practice.csv")#load the csv file

In [10]:
df.head()#shows the 1st 5 rows

   ID   Name  Gender   Age   County Attendance
0   1   Asha  Female  19.0   Kilifi        Yes
1   2   John    MALE  21.0  Mombasa        Yes
2   3   Mary  female  18.0  Kilifi          No
3   4    Ali    Male  22.0  MOMBASA        Yes
4   5  Amina  FEMALE   NaN   Kilifi        Yes

In [11]:
df.head(10)

   ID   Name  Gender   Age   County Attendance
0   1   Asha  Female  19.0   Kilifi        Yes
1   2   John    MALE  21.0  Mombasa        Yes
2   3   Mary  female  18.0  Kilifi          No
3   4    Ali    Male  22.0  MOMBASA        Yes
4   5  Amina  FEMALE   NaN   Kilifi        Yes
5   6  Peter    male  20.0  Mombasa        Yes
6   7   Asha  Female  19.0   Kilifi        Yes
7   8  Grace  FEMALE  17.0   Kilifi         No
8   9  David   Male   23.0  Mombasa        Yes
9  10  Sarah  female  18.0   Kilifi         No

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Gender      10 non-null     object
 3   Age         9 non-null      float64
 4   County      10 non-null     object
 5   Attendance  10 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 612.0+ bytes

In [16]:
df["Gender"]=df["Gender"].str.strip()

In [17]:
df["Gender"]=df["Gender"].str.lower()

In [18]:
df.head(10)

   ID   Name  Gender   Age   County Attendance
0   1   Asha  female  19.0   Kilifi        Yes
1   2   John    male  21.0  Mombasa        Yes
2   3   Mary  female  18.0  Kilifi          No
3   4    Ali    male  22.0  MOMBASA        Yes
4   5  Amina  female   NaN   Kilifi        Yes
5   6  Peter    male  20.0  Mombasa        Yes
6   7   Asha  female  19.0   Kilifi        Yes
7   8  Grace  female  17.0   Kilifi         No
8   9  David    male  23.0  Mombasa        Yes
9  10  Sarah  female  18.0   Kilifi         No

In [19]:
df["County"]=df["County"].str.strip().str.title()# it removes spaces be4 and after the string and convert it into title format

In [20]:
df.head(10)#shows 1st 10 rows

   ID   Name  Gender   Age   County Attendance
0   1   Asha  female  19.0   Kilifi        Yes
1   2   John    male  21.0  Mombasa        Yes
2   3   Mary  female  18.0   Kilifi         No
3   4    Ali    male  22.0  Mombasa        Yes
4   5  Amina  female   NaN   Kilifi        Yes
5   6  Peter    male  20.0  Mombasa        Yes
6   7   Asha  female  19.0   Kilifi        Yes
7   8  Grace  female  17.0   Kilifi         No
8   9  David    male  23.0  Mombasa        Yes
9  10  Sarah  female  18.0   Kilifi         No

In [28]:
df["Name"]=df["Name"].str.strip()#removes spaces before and after the string

In [22]:
df.head(10)#show 10 rows

   ID   Name  Gender   Age   County Attendance
0   1   Asha  female  19.0   Kilifi        Yes
1   2   John    male  21.0  Mombasa        Yes
2   3   Mary  female  18.0   Kilifi         No
3   4    Ali    male  22.0  Mombasa        Yes
4   5  Amina  female   NaN   Kilifi        Yes
5   6  Peter    male  20.0  Mombasa        Yes
6   7   Asha  female  19.0   Kilifi        Yes
7   8  Grace  female  17.0   Kilifi         No
8   9  David    male  23.0  Mombasa        Yes
9  10  Sarah  female  18.0   Kilifi         No

In [24]:
df.isnull()#returns false when there is no null value and true when there is null values (show missing values)

      ID   Name  Gender    Age  County  Attendance
0  False  False   False  False   False       False
1  False  False   False  False   False       False
2  False  False   False  False   False       False
3  False  False   False  False   False       False
4  False  False   False   True   False       False
5  False  False   False  False   False       False
6  False  False   False  False   False       False
7  False  False   False  False   False       False
8  False  False   False  False   False       False
9  False  False   False  False   False       False

In [27]:
df.isnull().sum()   #adds all the null values in the columns

ID            0
Name          0
Gender        0
Age           1
County        0
Attendance    0
dtype: int64

In [34]:
df['Age'].fillna(0)#does not change the original dataset automatically unless you tell pandas to do s0

0    19.0
1    21.0
2    18.0
3    22.0
4     0.0
5    20.0
6    19.0
7    17.0
8    23.0
9    18.0
Name: Age, dtype: float64

In [35]:
df.dropna()

   ID   Name  Gender   Age   County Attendance
0   1   Asha  female  19.0   Kilifi        Yes
1   2   John    male  21.0  Mombasa        Yes
2   3   Mary  female  18.0   Kilifi         No
3   4    Ali    male  22.0  Mombasa        Yes
4   5  Amina  female   0.0   Kilifi        Yes
5   6  Peter    male  20.0  Mombasa        Yes
6   7   Asha  female  19.0   Kilifi        Yes
7   8  Grace  female  17.0   Kilifi         No
8   9  David    male  23.0  Mombasa        Yes
9  10  Sarah  female  18.0   Kilifi         No

In [36]:
df["Age"]=df['Age'].fillna(0)#replaces null with 0 in the original dataset

In [37]:
df.head(10)

   ID   Name  Gender   Age   County Attendance
0   1   Asha  female  19.0   Kilifi        Yes
1   2   John    male  21.0  Mombasa        Yes
2   3   Mary  female  18.0   Kilifi         No
3   4    Ali    male  22.0  Mombasa        Yes
4   5  Amina  female   0.0   Kilifi        Yes
5   6  Peter    male  20.0  Mombasa        Yes
6   7   Asha  female  19.0   Kilifi        Yes
7   8  Grace  female  17.0   Kilifi         No
8   9  David    male  23.0  Mombasa        Yes
9  10  Sarah  female  18.0   Kilifi         No

In [38]:
df=df.drop_duplicates()

In [40]:
df.head(10)

   ID   Name  Gender   Age   County Attendance
0   1   Asha  female  19.0   Kilifi        Yes
1   2   John    male  21.0  Mombasa        Yes
2   3   Mary  female  18.0   Kilifi         No
3   4    Ali    male  22.0  Mombasa        Yes
4   5  Amina  female   0.0   Kilifi        Yes
5   6  Peter    male  20.0  Mombasa        Yes
6   7   Asha  female  19.0   Kilifi        Yes
7   8  Grace  female  17.0   Kilifi         No
8   9  David    male  23.0  Mombasa        Yes
9  10  Sarah  female  18.0   Kilifi         No

In [41]:
df.to_csv("cleaned_data.csv",index=False)

In [43]:
from google.colab import files

In [44]:
files.download("cleaned_data.csv")